server:
  port: 8081
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
  datasource:
#    url: jdbc:oracle:thin:@115.28.92.73:1521:xe
    url: jdbc:oracle:thin:@192.168.2.247:1522:xe
    username: sj_buzmgt
    password: sj_buzmgt1688
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    
    
